---
# tasks file for nginx
- name: install nginx
  become: true
  yum:
    name: nginx
    state: present

- name: ensure nginx is started and enabled
  become: true
  service:
    name: nginx
    state: started
    enabled: yes
    
- name: install php and its independencies
  become: true
  yum:
    name: 
      - php
      - php-mysqlnd
      - php-gd
      - php-curl
    state: present



   