---
<<<<<<< HEAD
- name: update web, db and nfs servers
=======
- name: update web, nfs and db servers
>>>>>>> 7e8f598da7772b80150ae0057ced0bfacd6ab89c
  hosts: webservers, nfs, db
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
    - name: ensure wireshark is at the latest version
      yum:
        name: wireshark
        state: latest

- name: update LB server
  hosts: lb
  remote_user: ubuntu
  become: yes
  become_user: root
  tasks:
    - name: Update apt repo
      apt: 
        update_cache: yes

    - name: ensure wireshark is at the latest version
      apt:
        name: wireshark
<<<<<<< HEAD
        state: latest

- name: Create directory 
  hosts: webservers, db, nfs
  remote_user: ec2-user
  become: yes
  become_user: root
  tasks:
   - name: create directory
     file:
      path: /home/file
      state: directory
=======
        state: latest
>>>>>>> 7e8f598da7772b80150ae0057ced0bfacd6ab89c
