# [nfs]
# 172.31.17.194 ansible_ssh_user='ec2-user'

# [uat-webservers]
# 172.31.42.119 ansible_ssh_user='ec2-user'
# 172.31.32.75 ansible_ssh_user='ec2-user'

# [db]
# 172.31.23.176 ansible_ssh_user='ec2-user'

# [lb]
# 172.31.22.55 ansible_ssh_user='ubuntu'
