 pipeline {
    agent any


    parameters {
      string(name: 'inventory', defaultValue: 'dev',  description: 'This is the inventory file for the environment to deploy configuration')
    }


    environment {
      ANSIBLE_CONFIG="${WORKSPACE}/deploy/ansible.cfg"
    }
    
    stages {
    stage("Initial cleanup") {
      steps {
        dir ("${WORKSPACE}") {
          deleteDir()
        }
      }
    }

    stage ('checkout SCM') {
      steps {

        git branch: "pj14" , url: "https://github.com/babslekson/ansible-config-mgt.git"

      }
    }

    stage ('prepare ansible for execution') {
      steps {
        sh 'echo ${WORKSPACE}'
        sh 'sed -i "3 a roles_path=${WORKSPACE}/roles" ${WORKSPACE}/deploy/ansible.cfg'
        }
      }


    stage ('Run ansible playbook') {
      steps {
        ansiblePlaybook become: true, colorized: true, credentialsId: 'private-key', disableHostKeyChecking: true, installation: 'ansible', inventory: 'inventory/${inventory}', playbook: 'playbooks/site.yml', vaultTmpPath: '' 
        }
    }

    stage('cleanup') {
      steps {
        cleanWs deleteDirs: true
      }
    }



    }
}