pipeline {
    agent any
	 
	stages {
		stage('Build') {
			steps {
				script {
					 sh 'echo "Building Stage"'
				}
			}
		}

		stage('Test') {
			steps {
				script {
					 sh 'echo "testing stage"'
				}
			}
		}
		stage('Deploy') {
			steps {
				script {
					 sh 'echo "deploying stage"'
				}
			}
		}
		stage('Cleanup') {
			steps {
				script {
					 sh 'echo "clean up stage"'
				}
			}
		}

		