---

- name: install EPEL repository
  yum: name=epel-release state=present
  when: >  # not for Fedora
    ansible_distribution == 'CentOS' or
    ansible_distribution == 'Red Hat Enterprise Linux'
  become: yes

- name: install python3 psycopg2
  yum:
    name:
      - python3-psycopg2
      - sudo
      - wget
      - perl
    state: present

- name: fixup some locale issues
  lineinfile:
    dest: /etc/default/locale
    line: 'LANGUAGE="{{ item }}"'
    state: present
    create: yes
  loop:
    - 'en_US:en'
    - 'en_us.UTF-8'

- name: Install the repository RPM
  yum:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-8-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
  become: yes

- name: Disable the built-in PostgreSQL module
  command: yum -qy module disable postgresql
  become: yes

- name: install postgres packages
  yum:
    name:
      - postgresql{{ postgres_server_pkg_version }}-server
      - postgresql{{ postgres_server_pkg_version }}-contrib
      - postgresql{{ postgres_server_pkg_version }}-devel
    state: present
  become: yes
