---
- hosts: db
  tasks:
    - name: Installing database
    - import_playbook: ../static-assignments/database.yml
  tags:
    - always

- hosts: nginx
  tasks: 
    - name: installing nginx (reverse proxy)
    - import_playbook: ../static-assignments/nginx.yml

