---
# - hosts: db
# - name: Installing database
#   import_playbook: ../static-assignments/database.yml
#   tags:
#     - always

  - hosts: todo
  - name: deploying todo application
    import_playbook: ../static-assignments/deployment.yml
# - hosts: nginx
# - name: installing nginx (reverse proxy)
#   import_playbook: ../static-assignments/nginx.yml

# - hosts: artifactory
# - name: artifactory repository
#   import_playbook: ../static-assignments/artifactory.yml

# - hosts: postgres
# - name: postgress for artifactory
#   import_playbook: ../static-assignments/postgres.yml
