---
- hosts: db
- name: Installing reverse proxy
  tasks:
  import_playbook: ../static-assignments/database.yml
  tags:
    - always

- hosts: nginx
- name: nginx assignment
  import_playbook: ../static-assignments/nginx.yml

