---
# tasks file for artifactory

- name: Install PostgreSQL and related packages
  become: yes
  ansible.builtin.yum:
    name:
      - postgresql-server
      - postgresql-contrib
    state: present

- name: Initialize PostgreSQL database
  become: yes
  ansible.builtin.command: /usr/bin/postgresql-setup --initdb
  when: pgsql_data_dir.stat.exists == False or pgsql_data_dir_empty.rc == 0
  register: postgresql_init
  ignore_errors: true

- name: Start and enable PostgreSQL service
  become: yes
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: yes


- name: Install pip
  ansible.builtin.yum:
    name: python3-pip
    state: present


- name: Make sure psycopg2 is installed - needed for ansible postgresql stuff
  ansible.builtin.pip:
    name: psycopg2
    state: present
    become: true

- name: Create PostgreSQL database for Artifactory
  become: yes
  become_user: postgres
  postgresql_db:
    name: artifactory

- name: Create PostgreSQL user for Artifactory
  become: yes
  become_user: postgres
  postgresql_user:
    name: artifactory
    password: your_secure_password

- name: install java 11
  ansible.builtin.yum:
    name: java-11-openjdk-devel
    state: present

- name: install java 11
  ansible.builtin.yum:
    name: 
      - wget
      - unzip
    state: present

- name: Configuring java path
  ansible.builtin.template:
    src: templates/bash-profile.j2
    dest: .bash_profile
  

- name: reload the /etc/profile
  shell: source ~/.bash_profile


- name: add the repository key to repos list
  ansible.builtin.get_url:
    url:  https://releases.jfrog.io/artifactory/artifactory-rpms/artifactory-rpms.repo 
    dest: /home/ec2-user/jfrog-artifactory-rpms.repo
    mode: '0755'
 
- name: Copy the downloaded file to the etc repo
  ansible.builtin.copy:
    src: /home/ec2-user/jfrog-artifactory-rpms.repo
    dest: /etc/yum.repos.d/jfrog-artifactory-rpms.repo
    remote_src: yes
    follow: yes

- name: update cache
  ansible.builtin.yum:
    update_cache: yes

- name: install artifactory
  ansible.builtin.yum:
    name: jfrog-artifactory-oss
    state: present

- name: start and enable artifactory
  ansible.builtin.service:
    name: artifactory
    state: started
    enabled: yes

- name: Download PostgreSQL JDBC driver
  ansible.builtin.get_url:
    url: "{{ postgres_driver_download_url }}"
    dest: "{{ artifactory_home }}/app/artifactory/tomcat/lib/"
